export const USER_NOT_FOUND = 'USER_NOT_FOUND';
export const INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR';
export const INVALID_CREDENTIALS = 'INVALID_CREDENTIALS';
export const EMAIL_ALREADY_EXISTS = 'EMAIL_ALREADY_EXISTS';
export const BAD_REQUEST = 'BAD_REQUEST';